"""decky-secrets backend package."""

from .auth import (
    DEFAULT_DELETE_ON_FAILURE_THRESHOLD,
    DEFAULT_FULL_RELOCK_TIMEOUT_SECONDS,
    DEFAULT_LONG_WINDOW_ATTEMPTS,
    DEFAULT_LONG_WINDOW_SECONDS,
    DEFAULT_SESSION_ACCESS_WINDOW_SECONDS,
    DEFAULT_SHORT_WINDOW_ATTEMPTS,
    DEFAULT_SHORT_WINDOW_SECONDS,
    AccessStateError,
    AuthConfig,
    AuthenticationError,
    AuthenticationLockedError,
    AuthStatus,
    CallerType,
    VaultAuthManager,
    VaultState,
)
from .vault import (
    CURRENT_BLOB_VERSION,
    CURRENT_KDF_ALGORITHM,
    CURRENT_KDF_ITERATIONS,
    CURRENT_PIN_KDF_ITERATIONS,
    VAULT_DIR_NAME,
    VAULT_FILE_NAME,
    VaultBlobError,
    VaultFileStore,
    VaultRecord,
    VaultPayload,
    VaultPayloadPin,
    VaultPayloadVault,
    create_recovery_key,
)

__all__ = [
    "CURRENT_BLOB_VERSION",
    "CURRENT_KDF_ALGORITHM",
    "CURRENT_KDF_ITERATIONS",
    "CURRENT_PIN_KDF_ITERATIONS",
    "DEFAULT_DELETE_ON_FAILURE_THRESHOLD",
    "DEFAULT_FULL_RELOCK_TIMEOUT_SECONDS",
    "DEFAULT_LONG_WINDOW_ATTEMPTS",
    "DEFAULT_LONG_WINDOW_SECONDS",
    "DEFAULT_SESSION_ACCESS_WINDOW_SECONDS",
    "DEFAULT_SHORT_WINDOW_ATTEMPTS",
    "DEFAULT_SHORT_WINDOW_SECONDS",
    "VAULT_DIR_NAME",
    "VAULT_FILE_NAME",
    "AccessStateError",
    "AuthConfig",
    "AuthenticationError",
    "AuthenticationLockedError",
    "AuthStatus",
    "CallerType",
    "VaultAuthManager",
    "VaultBlobError",
    "VaultFileStore",
    "VaultPayload",
    "VaultPayloadPin",
    "VaultPayloadVault",
    "VaultRecord",
    "VaultState",
    "create_recovery_key",
]
